version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/client/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
